// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

namespace MpvPlayer.Core.Args;

public sealed class InitializeArgument
{
    public InitializeArgument()
    {
    }

    public InitializeArgument(
        string configFile,
        bool autoPlay = true,
        Func<string, IntPtr> func = default)
    {
        ConfigFile = configFile;
        AutoPlay = autoPlay;
        if (func != null)
        {
            OpenGLGetProcAddress = func;
        }
    }

    public string ConfigFile { get; init; }

    public bool AutoPlay { get; set; }

    public Func<string, IntPtr> OpenGLGetProcAddress { get; init; }
}
