// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

using Bili.Copilot.Libs.Mpv.Enums.Client;

namespace Bili.Copilot.Libs.Mpv.Args;

public sealed class LogMessageReceivedEventArgs : EventArgs
{
    public string Prefix { get; set; }

    public string Message { get; set; }

    public MpvLogLevel Level { get; set; }

    public LogMessageReceivedEventArgs(string prefix, string message, MpvLogLevel level)
    {
        Prefix = prefix;
        Message = message;
        Level = level;
    }
}
