// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

namespace MpvPlayer.Core.Args;

public sealed class PlaybackPositionChangedEventArgs : EventArgs
{
    public PlaybackPositionChangedEventArgs(long duration, long position)
    {
        Duration = duration;
        Position = position;
    }

    /// <summary>
    /// Gets or sets the duration in milliseconds of the media item.
    /// </summary>
    public long Duration { get; set; }

    /// <summary>
    /// Gets or sets the position in milliseconds of the media item.
    /// </summary>
    public long Position { get; set; }
}
