// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

using MpvPlayer.Core.Enums.Player;

namespace MpvPlayer.Core.Args;

public sealed class PlaybackStateChangedEventArgs : EventArgs
{
    public PlaybackStateChangedEventArgs(PlaybackState oldState, PlaybackState newState)
    {
        OldState = oldState;
        NewState = newState;
    }

    /// <summary>
    /// The old state of the player.
    /// </summary>
    public PlaybackState OldState { get; init; }

    /// <summary>
    /// The new state of the player.
    /// </summary>
    public PlaybackState NewState { get; init; }
}
