// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

namespace Bili.Copilot.Libs.Mpv.Args;

public sealed class PlaybackStoppedEventArgs : EventArgs
{
    public PlaybackStoppedEventArgs(bool isInterrupted, string message = "")
    {
        IsInterrupted = isInterrupted;
        ErrorMessage = message;
    }

    /// <summary>
    /// Gets a value indicating whether the playback was interrupted.
    /// </summary>
    public bool IsInterrupted { get; init; }

    /// <summary>
    /// Gets error message if the playback was interrupted.
    /// </summary>
    public string ErrorMessage { get; init; }
}
