// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

using System.Runtime.InteropServices;
using MpvPlayer.Core.Enums.Client;
using MpvPlayer.Core.Enums.Render;
using MpvPlayer.Core.Structs.Client;
using MpvPlayer.Core.Structs.Render;

namespace MpvPlayer.Core.Interop;

public partial class MpvRenderContextNative
{
    [LibraryImport(Mpv)]
    private static partial MpvError mpv_render_context_create(out MpvRenderContextHandle context, MpvHandle handle, MpvRenderParam[] param);

    [LibraryImport(Mpv)]
    private static partial MpvError mpv_render_context_set_parameter(MpvRenderContextHandle context, MpvRenderParam param);

    [LibraryImport(Mpv)]
    private static partial MpvError mpv_render_context_get_info(MpvRenderContextHandle context, MpvRenderParam param);

    [LibraryImport(Mpv)]
    private static partial MpvError mpv_render_context_set_update_callback(MpvRenderContextHandle context, MpvRenderUpdateCallback callback, IntPtr callbackContext);

    [LibraryImport(Mpv)]
    private static partial MpvRenderUpdateFlag mpv_render_context_update(MpvRenderContextHandle context);

    [LibraryImport(Mpv)]
    private static partial MpvError mpv_render_context_render(MpvRenderContextHandle context, MpvRenderParam[] param);

    [LibraryImport(Mpv)]
    private static partial MpvError mpv_render_context_report_swap(MpvRenderContextHandle context);

    [LibraryImport(Mpv)]
    private static partial void mpv_render_context_free(MpvRenderContextHandle context);

    [LibraryImport("gl")]
    private static partial void glGetIntegerv(int pname, out int data);

    public delegate void MpvRenderUpdateCallback(IntPtr callbackCtx);
}
