// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

using Microsoft.Windows.Widgets.Providers;

namespace Bili.Copilot.App.NativeServices.Widgets;

public interface IWidget
{
    string Id { get; }
    string State { get; }

    bool IsActivated { get; }

    void Activate();
    void Deactivate();
    void OnActionInvoked(WidgetActionInvokedArgs actionInvokedArgs);
    void OnWidgetContextChanged(WidgetContextChangedArgs contextChangedArgs);
    string GetTemplateForWidget();
    string GetDataForWidget();
}
