// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

using System.Runtime.InteropServices;

namespace Bili.Copilot.Libs.Mpv.Structs.RenderGL;

/// <summary>Deprecated. For Mpv_RENDER_PARAM_DRM_DISPLAY.</summary>
[StructLayout(LayoutKind.Sequential, Size = 32)]
public struct MpvOpenGLDRMParams
{
    public int Fd;

    public int CrtcId;

    public int ConnectorId;

    public IntPtr AtomicRequestPtr; //WAT

    public int RenderFd;
}
