// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

namespace MpvPlayer.Core.Enums.Player;

public enum PlaybackState
{
    /// <summary>
    /// No current state.
    /// </summary>
    None = 0,

    /// <summary>
    /// A media item is opening.
    /// </summary>
    Opening,

    /// <summary>
    /// A media item is decoding.
    /// </summary>
    Decoding,

    /// <summary>
    /// A media item is buffering.
    /// </summary>
    Buffering,

    /// <summary>
    /// A media item is playing.
    /// </summary>
    Playing,

    /// <summary>
    /// A media item is paused.
    /// </summary>
    Paused,
}
